SUPABASE_URL= "https://xnjucpicyeyxcpjfunze.supabase.co"
OPENAI_API_KEY = "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"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhuanVjcGljeWV5eGNwamZ1bnplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAxOTY3NzksImV4cCI6MjA4NTc3Mjc3OX0.65UCXQ-8-Pz8V5CguKqkx5z3q8W8BmBkQaHRtL_BJ_k"
NOAA_TOKEN="HhUaOerdUbSiEFwTltmQUwIvuCypEyvQ"
# optional:
OPENAI_MODEL="gpt-4.1-mini"